name: "hono-next-example--prod"

services:

  db:
    image: postgres:14.17
    restart: always
    environment:
      PGPORT: ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  db-migrate:
    image: backend_app
    command: |
      bun db:push
    depends_on:
      - db

  backend_app:
    build:
      context: .
      dockerfile: packages/backend_app/Dockerfile
      target: release
    ports:
      - "${BACKEND_APP_PORT}:${BACKEND_APP_PORT}"
    depends_on:
      - db-migrate

  frontend_app:
    build:
      context: .
      dockerfile: packages/frontend_app/Dockerfile
      target: runner
      args:
        BACKEND_APP_SERVER_URL: http://backend_app:4300
        NEXT_PUBLIC_BACKEND_APP_URL: http://localhost:4300
    ports:
      - "${FRONTEND_APP_PORT}:${FRONTEND_APP_PORT}"
    depends_on:
      - backend_app
