name: "hono-next-example--dev"

services:
  db:
    image: postgres:14.16
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data

  db-migrate:
    image: backend_app
    env_file:
      - .env
    command: |
      bun run db:push
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - db

  backend_app:
    image: backend_app
    build:
      context: .
      dockerfile: packages/backend_app/Dockerfile
      target: dev
    env_file:
      - .env
    command: |
      bun run --hot src/server.ts
    ports:
      - "${BACKEND_APP_PORT}:${BACKEND_APP_PORT}"
    depends_on:
      - db
      - db-migrate
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  frontend_app:
    build:
      context: .
      dockerfile: packages/frontend_app/Dockerfile
      target: dev
    env_file:
      - .env
    command: |
      bun run dev --port ${FRONTEND_APP_PORT}
    ports:
      - "${FRONTEND_APP_PORT}:${FRONTEND_APP_PORT}"
    depends_on:
      - backend_app
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  export-openapi:
    image: backend_app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: |
      bun run --hot src/scripts/export-openapi/index.ts

volumes:
  db-store:
  node_modules:
