import "./globals.css";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies, headers } from "next/headers";
import { RootProviders } from "../lib/RootProviders";
import {
  defaultLocale,
  isLocale,
  PATHNAME_LOCALE_HEADER,
} from "../locales/constants";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "hono-next-example",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerStore = await headers();
  const pathnameLocale = headerStore.get(PATHNAME_LOCALE_HEADER);
  const cookieStore = await cookies();
  const cookieLocale = cookieStore.get("Next-Locale")?.value;
  const lang =
    pathnameLocale && isLocale(pathnameLocale)
      ? pathnameLocale
      : cookieLocale && isLocale(cookieLocale)
        ? cookieLocale
        : defaultLocale;

  return (
    <html lang={lang} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootProviders>{children}</RootProviders>
      </body>
    </html>
  );
}
