name: Backend App

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: example-db
  POSTGRES_PORT: 5432
  BACKEND_APP_PORT: 4300
  DATABASE_HOST: 127.0.0.1
  SUPABASE_URL: https://example.supabase.com
  SUPABASE_KEY: example-key
  NEXT_PUBLIC_BACKEND_APP_URL: http://localhost:4300
  NEXT_PUBLIC_SUPABASE_URL: http://localhost:8000
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: test
  BACKEND_APP_SERVER_URL: http://localhost:4300
  FRONTEND_APP_SERVER_URL: http://localhost
  FRONTEND_APP_PORT: 4400
  HOSTNAME: localhost

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v5

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - '.github/workflows/backend-app.yml'
              - 'packages/backend_app/**'
              - '.tool-versions'
              - 'biome.jsonc'
              - 'tsconfig.json'
            frontend:
              - '.github/workflows/frontend-app.yml'
              - 'packages/backend_app/openapi.json'
              - 'packages/frontend_app/**'
              - '.tool-versions'
              - 'biome.jsonc'
              - 'tsconfig.json'
            e2e:
              - '.github/workflows/e2e.yml'
              - 'packages/e2e/**'
              - '.dockerignore'
              - '.tool-versions'
              - 'biome.jsonc'
              - 'docker/**'
              - 'tsconfig.json'

    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      e2e: ${{ steps.filter.outputs.e2e }}

  backend-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    defaults:
      run:
        working-directory: ./packages/backend_app
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun install --frozen-lockfile

      - name: Check gen:openapi diff
        run: |
          bun run gen:openapi
          git add -N openapi.json
          git diff --exit-code openapi.json

      - run: bun run lint

      - run: bun run typecheck

  backend-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs:
      - backend-check
    defaults:
      run:
        working-directory: ./packages/backend_app
    services:
      postgres:
        image: postgres:17.6
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          PGPORT: ${{ env.POSTGRES_PORT }}
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun install --frozen-lockfile

      - run: bun db:push

      - run: bun test --coverage

  frontend-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: changes
    if: needs.changes.outputs.frontend == 'true'
    defaults:
      run:
        working-directory: ./packages/frontend_app
    steps:
      - uses: actions/checkout@v5

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun install --frozen-lockfile

      - name: Check gen:client diff
        run: |
          bun run gen:client
          git add -N src/client
          git diff --exit-code src/client

      - run: bun run lint

      - run: bun run typecheck

  frontend-test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs:
      - frontend-check
    defaults:
      run:
        working-directory: ./packages/frontend_app
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.55.1-noble
    steps:
      - uses: actions/checkout@v5

      - name: Install required tools
        run: |
          apt-get update
          apt-get install -y unzip

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun install --frozen-lockfile

      - run: bun run test-storybook --coverage

  frontend-chromatic:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    needs:
      - frontend-test
    if: github.event.pull_request.draft != true
    defaults:
      run:
        working-directory: ./packages/frontend_app
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Chromatic
        uses: chromaui/action@v13
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/frontend_app
          exitZeroOnChanges: false

  e2e-check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: changes
    if: needs.changes.outputs.e2e == 'true'
    defaults:
      run:
        working-directory: ./packages/e2e
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version-file: .tool-versions

      - run: npm ci

      - run: npm run lint

      - run: npm run typecheck

  e2e-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - backend-test
      - frontend-test
      - e2e-check
    if: >-
      github.event.pull_request.draft != true &&
      (needs.backend-test.result == 'success' || needs.backend-test.result == 'skipped') &&
      (needs.frontend-test.result == 'success' || needs.frontend-test.result == 'skipped') &&
      (needs.e2e-check.result == 'success' || needs.e2e-check.result == 'skipped')
    steps:
      - uses: actions/checkout@v5

      - run: cp .env.example .env
        working-directory: ./docker

      - name: docker compose build
        run: docker compose -f docker-compose.supabase.yml -f docker-compose.prod.yml build
        working-directory: ./docker

      - name: docker compose up studio
        run: docker compose -f docker-compose.supabase.yml -f docker-compose.prod.yml up -d studio
        working-directory: ./docker

      - name: docker compose up frontend_app
        run: docker compose -f docker-compose.supabase.yml -f docker-compose.prod.yml up -d frontend_app
        working-directory: ./docker

      - name: docker compose up e2e
        run: docker compose -f docker-compose.supabase.yml -f docker-compose.prod.yml up e2e --exit-code-from e2e
        working-directory: ./docker

      - name: docker compose logs
        if: failure()
        run: docker compose -f docker-compose.supabase.yml -f docker-compose.prod.yml logs
        working-directory: ./docker

      # NOTE: npx playwright show-report name-of-my-extracted-playwright-report
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: "playwright-report-${{ github.sha }}"
          path: packages/e2e/playwright-report/
          retention-days: 1

      - name: docker compose down
        if: always()
        run: docker compose -f docker-compose.supabase.yml -f docker-compose.prod.yml down --rmi all --volumes --remove-orphans
        working-directory: ./docker
