name: Frontend App

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./packages/frontend_app

env:
  NEXT_PUBLIC_BACKEND_APP_URL: http://localhost:4300

jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'packages/backend_app/**'
            frontend:
              - '.github/workflows/frontend-app.yml'
              - 'packages/frontend_app/**'
              - '.tool-versions'
              - 'biome.jsonc'
              - 'tsconfig.json'
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}

  check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: changes
    if: needs.changes.outputs.backend == 'true' || needs.changes.outputs.frontend == 'true' 
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun install --frozen-lockfile

      - run: bun run lint

      - run: bun run typecheck

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs:
      - changes
      - check
    if: github.event.pull_request.draft != true && needs.changes.outputs.frontend == 'true' && needs.check.result == 'success' 
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.55.0-noble
    steps:
      - uses: actions/checkout@v4

      - name: Install required tools
        run: |
          apt-get update
          apt-get install -y unzip

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun install --frozen-lockfile

      - run: bun run test-storybook --coverage

  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs:
      - changes
      - check
      - test
    if: github.event.pull_request.draft != true && needs.changes.outputs.frontend == 'true' && needs.test.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run Chromatic
        uses: chromaui/action@v13
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: packages/frontend_app
          exitZeroOnChanges: false
