name: Frontend App

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./packages/frontend_app

env:
  NEXT_PUBLIC_BACKEND_APP_URL: http://localhost:4300

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun install --frozen-lockfile

      - run: bun run lint

      - run: bun run typecheck

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.pull_request.draft != true
    container:
      # Make sure to grab the latest version of the Playwright image
      # https://playwright.dev/docs/docker#pull-the-image
      image: mcr.microsoft.com/playwright:v1.55.0-noble
    steps:
      - uses: actions/checkout@v4

      - name: Install required tools
        run: |
          apt-get update
          apt-get install -y unzip

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - run: bun install --frozen-lockfile

      - run: bun run test-storybook --coverage

  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build storybook
        run: bun run build-storybook

      - name: Run Chromatic
        uses: chromaui/action@v13
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
