/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend_app OpenAPI
 * OpenAPI spec version: 1.0.0
 */

import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
  DeletePostsId404,
  DeletePostsId500,
  ErrorResponse,
  GetPosts200,
  GetPosts404,
  GetPosts500,
  PostPosts200,
  PostPosts404,
  PostPosts500,
  PostPostsBody,
  PutPostsId200,
  PutPostsId404,
  PutPostsId500,
  PutPostsIdBody,
} from "./index.schemas";

export type getPostsResponse200 = {
  data: GetPosts200;
  status: 200;
};

export type getPostsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type getPostsResponse404 = {
  data: GetPosts404;
  status: 404;
};

export type getPostsResponse500 = {
  data: GetPosts500;
  status: 500;
};

export type getPostsResponseComposite =
  | getPostsResponse200
  | getPostsResponse400
  | getPostsResponse404
  | getPostsResponse500;

export type getPostsResponse = getPostsResponseComposite & {
  headers: Headers;
};

export const getGetPostsUrl = () => {
  return `/posts`;
};

export const getPosts = async (
  options?: RequestInit,
): Promise<getPostsResponse> => {
  const res = await fetch(getGetPostsUrl(), {
    ...options,
    method: "GET",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: getPostsResponse["data"] = body ? JSON.parse(body) : {};

  return { data, status: res.status, headers: res.headers } as getPostsResponse;
};

export const getGetPostsQueryKey = () => {
  return [`/posts`] as const;
};

export const getGetPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorResponse | GetPosts404 | GetPosts500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
  >;
  fetch?: RequestInit;
}) => {
  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPosts>>> = ({
    signal,
  }) => getPosts({ signal, ...fetchOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPosts>>
>;
export type GetPostsQueryError = ErrorResponse | GetPosts404 | GetPosts500;

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorResponse | GetPosts404 | GetPosts500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorResponse | GetPosts404 | GetPosts500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPosts>>,
          TError,
          Awaited<ReturnType<typeof getPosts>>
        >,
        "initialData"
      >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorResponse | GetPosts404 | GetPosts500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetPosts<
  TData = Awaited<ReturnType<typeof getPosts>>,
  TError = ErrorResponse | GetPosts404 | GetPosts500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getPosts>>, TError, TData>
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPostsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export type postPostsResponse200 = {
  data: PostPosts200;
  status: 200;
};

export type postPostsResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type postPostsResponse404 = {
  data: PostPosts404;
  status: 404;
};

export type postPostsResponse500 = {
  data: PostPosts500;
  status: 500;
};

export type postPostsResponseComposite =
  | postPostsResponse200
  | postPostsResponse400
  | postPostsResponse404
  | postPostsResponse500;

export type postPostsResponse = postPostsResponseComposite & {
  headers: Headers;
};

export const getPostPostsUrl = () => {
  return `/posts`;
};

export const postPosts = async (
  postPostsBody: PostPostsBody,
  options?: RequestInit,
): Promise<postPostsResponse> => {
  const res = await fetch(getPostPostsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(postPostsBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: postPostsResponse["data"] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as postPostsResponse;
};

export const getPostPostsMutationOptions = <
  TError = ErrorResponse | PostPosts404 | PostPosts500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPosts>>,
    TError,
    { data: PostPostsBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: PostPostsBody },
  TContext
> => {
  const mutationKey = ["postPosts"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPosts>>,
    { data: PostPostsBody }
  > = (props) => {
    const { data } = props ?? {};

    return postPosts(data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPosts>>
>;
export type PostPostsMutationBody = PostPostsBody;
export type PostPostsMutationError =
  | ErrorResponse
  | PostPosts404
  | PostPosts500;

export const usePostPosts = <
  TError = ErrorResponse | PostPosts404 | PostPosts500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPosts>>,
      TError,
      { data: PostPostsBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postPosts>>,
  TError,
  { data: PostPostsBody },
  TContext
> => {
  const mutationOptions = getPostPostsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export type putPostsIdResponse200 = {
  data: PutPostsId200;
  status: 200;
};

export type putPostsIdResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type putPostsIdResponse404 = {
  data: PutPostsId404;
  status: 404;
};

export type putPostsIdResponse500 = {
  data: PutPostsId500;
  status: 500;
};

export type putPostsIdResponseComposite =
  | putPostsIdResponse200
  | putPostsIdResponse400
  | putPostsIdResponse404
  | putPostsIdResponse500;

export type putPostsIdResponse = putPostsIdResponseComposite & {
  headers: Headers;
};

export const getPutPostsIdUrl = (id: number) => {
  return `/posts/${id}`;
};

export const putPostsId = async (
  id: number,
  putPostsIdBody: PutPostsIdBody,
  options?: RequestInit,
): Promise<putPostsIdResponse> => {
  const res = await fetch(getPutPostsIdUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(putPostsIdBody),
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: putPostsIdResponse["data"] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as putPostsIdResponse;
};

export const getPutPostsIdMutationOptions = <
  TError = ErrorResponse | PutPostsId404 | PutPostsId500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putPostsId>>,
    TError,
    { id: number; data: PutPostsIdBody },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putPostsId>>,
  TError,
  { id: number; data: PutPostsIdBody },
  TContext
> => {
  const mutationKey = ["putPostsId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putPostsId>>,
    { id: number; data: PutPostsIdBody }
  > = (props) => {
    const { id, data } = props ?? {};

    return putPostsId(id, data, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutPostsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putPostsId>>
>;
export type PutPostsIdMutationBody = PutPostsIdBody;
export type PutPostsIdMutationError =
  | ErrorResponse
  | PutPostsId404
  | PutPostsId500;

export const usePutPostsId = <
  TError = ErrorResponse | PutPostsId404 | PutPostsId500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putPostsId>>,
      TError,
      { id: number; data: PutPostsIdBody },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putPostsId>>,
  TError,
  { id: number; data: PutPostsIdBody },
  TContext
> => {
  const mutationOptions = getPutPostsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};

export type deletePostsIdResponse200 = {
  data: null;
  status: 200;
};

export type deletePostsIdResponse400 = {
  data: ErrorResponse;
  status: 400;
};

export type deletePostsIdResponse404 = {
  data: DeletePostsId404;
  status: 404;
};

export type deletePostsIdResponse500 = {
  data: DeletePostsId500;
  status: 500;
};

export type deletePostsIdResponseComposite =
  | deletePostsIdResponse200
  | deletePostsIdResponse400
  | deletePostsIdResponse404
  | deletePostsIdResponse500;

export type deletePostsIdResponse = deletePostsIdResponseComposite & {
  headers: Headers;
};

export const getDeletePostsIdUrl = (id: number) => {
  return `/posts/${id}`;
};

export const deletePostsId = async (
  id: number,
  options?: RequestInit,
): Promise<deletePostsIdResponse> => {
  const res = await fetch(getDeletePostsIdUrl(id), {
    ...options,
    method: "DELETE",
  });

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  const data: deletePostsIdResponse["data"] = body ? JSON.parse(body) : {};

  return {
    data,
    status: res.status,
    headers: res.headers,
  } as deletePostsIdResponse;
};

export const getDeletePostsIdMutationOptions = <
  TError = ErrorResponse | DeletePostsId404 | DeletePostsId500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePostsId>>,
    TError,
    { id: number },
    TContext
  >;
  fetch?: RequestInit;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePostsId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deletePostsId"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, fetch: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePostsId>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deletePostsId(id, fetchOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePostsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePostsId>>
>;

export type DeletePostsIdMutationError =
  | ErrorResponse
  | DeletePostsId404
  | DeletePostsId500;

export const useDeletePostsId = <
  TError = ErrorResponse | DeletePostsId404 | DeletePostsId500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePostsId>>,
      TError,
      { id: number },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePostsId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationOptions = getDeletePostsIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
