/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend_app OpenAPI
 * OpenAPI spec version: 1.0.0
 */
export type ErrorResponseCode =
  (typeof ErrorResponseCode)[keyof typeof ErrorResponseCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorResponseCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export interface ErrorResponse {
  code: ErrorResponseCode;
  /** explanation */
  message: string;
}

export interface Post {
  /**
   * Primary ID
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  user_id: number;
  /** The content of the post */
  content: string;
  /** The date and time the post was created */
  created_at: string;
  /** The date and time the post was updated */
  updated_at: string;
}

export type PostUserSignup401AllOfCode =
  (typeof PostUserSignup401AllOfCode)[keyof typeof PostUserSignup401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUserSignup401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostUserSignup401AllOf = {
  code?: PostUserSignup401AllOfCode;
  /** explanation */
  message?: string;
};

export type PostUserSignup401 = ErrorResponse & PostUserSignup401AllOf;

export type PostUserSignup403AllOfCode =
  (typeof PostUserSignup403AllOfCode)[keyof typeof PostUserSignup403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUserSignup403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostUserSignup403AllOf = {
  code?: PostUserSignup403AllOfCode;
  /** explanation */
  message?: string;
};

export type PostUserSignup403 = ErrorResponse & PostUserSignup403AllOf;

export type PostUserSignup404AllOfCode =
  (typeof PostUserSignup404AllOfCode)[keyof typeof PostUserSignup404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUserSignup404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostUserSignup404AllOf = {
  code?: PostUserSignup404AllOfCode;
  /** explanation */
  message?: string;
};

export type PostUserSignup404 = ErrorResponse & PostUserSignup404AllOf;

export type PostUserSignup500AllOfCode =
  (typeof PostUserSignup500AllOfCode)[keyof typeof PostUserSignup500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUserSignup500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostUserSignup500AllOf = {
  code?: PostUserSignup500AllOfCode;
  /** explanation */
  message?: string;
};

export type PostUserSignup500 = ErrorResponse & PostUserSignup500AllOf;

export type GetPosts200 = {
  posts: Post[];
};

export type GetPosts401AllOfCode =
  (typeof GetPosts401AllOfCode)[keyof typeof GetPosts401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts401AllOf = {
  code?: GetPosts401AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts401 = ErrorResponse & GetPosts401AllOf;

export type GetPosts403AllOfCode =
  (typeof GetPosts403AllOfCode)[keyof typeof GetPosts403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts403AllOf = {
  code?: GetPosts403AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts403 = ErrorResponse & GetPosts403AllOf;

export type GetPosts404AllOfCode =
  (typeof GetPosts404AllOfCode)[keyof typeof GetPosts404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts404AllOf = {
  code?: GetPosts404AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts404 = ErrorResponse & GetPosts404AllOf;

export type GetPosts500AllOfCode =
  (typeof GetPosts500AllOfCode)[keyof typeof GetPosts500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts500AllOf = {
  code?: GetPosts500AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts500 = ErrorResponse & GetPosts500AllOf;

export type PostPostsBody = {
  /**
   * The content of the post
   * @minLength 1
   */
  content: string;
};

export type PostPosts200 = {
  post: Post;
};

export type PostPosts401AllOfCode =
  (typeof PostPosts401AllOfCode)[keyof typeof PostPosts401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts401AllOf = {
  code?: PostPosts401AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts401 = ErrorResponse & PostPosts401AllOf;

export type PostPosts403AllOfCode =
  (typeof PostPosts403AllOfCode)[keyof typeof PostPosts403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts403AllOf = {
  code?: PostPosts403AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts403 = ErrorResponse & PostPosts403AllOf;

export type PostPosts404AllOfCode =
  (typeof PostPosts404AllOfCode)[keyof typeof PostPosts404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts404AllOf = {
  code?: PostPosts404AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts404 = ErrorResponse & PostPosts404AllOf;

export type PostPosts500AllOfCode =
  (typeof PostPosts500AllOfCode)[keyof typeof PostPosts500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts500AllOf = {
  code?: PostPosts500AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts500 = ErrorResponse & PostPosts500AllOf;

export type PutPostsIdBody = {
  /**
   * The content of the post
   * @minLength 1
   */
  content?: string;
};

export type PutPostsId200 = {
  post: Post;
};

export type PutPostsId401AllOfCode =
  (typeof PutPostsId401AllOfCode)[keyof typeof PutPostsId401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsId401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsId401AllOf = {
  code?: PutPostsId401AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsId401 = ErrorResponse & PutPostsId401AllOf;

export type PutPostsId403AllOfCode =
  (typeof PutPostsId403AllOfCode)[keyof typeof PutPostsId403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsId403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsId403AllOf = {
  code?: PutPostsId403AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsId403 = ErrorResponse & PutPostsId403AllOf;

export type PutPostsId404AllOfCode =
  (typeof PutPostsId404AllOfCode)[keyof typeof PutPostsId404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsId404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsId404AllOf = {
  code?: PutPostsId404AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsId404 = ErrorResponse & PutPostsId404AllOf;

export type PutPostsId500AllOfCode =
  (typeof PutPostsId500AllOfCode)[keyof typeof PutPostsId500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsId500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsId500AllOf = {
  code?: PutPostsId500AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsId500 = ErrorResponse & PutPostsId500AllOf;

export type DeletePostsId401AllOfCode =
  (typeof DeletePostsId401AllOfCode)[keyof typeof DeletePostsId401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsId401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsId401AllOf = {
  code?: DeletePostsId401AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsId401 = ErrorResponse & DeletePostsId401AllOf;

export type DeletePostsId403AllOfCode =
  (typeof DeletePostsId403AllOfCode)[keyof typeof DeletePostsId403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsId403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsId403AllOf = {
  code?: DeletePostsId403AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsId403 = ErrorResponse & DeletePostsId403AllOf;

export type DeletePostsId404AllOfCode =
  (typeof DeletePostsId404AllOfCode)[keyof typeof DeletePostsId404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsId404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsId404AllOf = {
  code?: DeletePostsId404AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsId404 = ErrorResponse & DeletePostsId404AllOf;

export type DeletePostsId500AllOfCode =
  (typeof DeletePostsId500AllOfCode)[keyof typeof DeletePostsId500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsId500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsId500AllOf = {
  code?: DeletePostsId500AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsId500 = ErrorResponse & DeletePostsId500AllOf;
