/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend_app OpenAPI
 * OpenAPI spec version: 1.0.0
 */
export type ErrorResponseCode =
  (typeof ErrorResponseCode)[keyof typeof ErrorResponseCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorResponseCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export interface ErrorResponse {
  code: ErrorResponseCode;
  /** explanation */
  message: string;
}

export interface User {
  public_id: string;
  display_name: string;
}

export interface Post {
  /** Public ID */
  public_id: string;
  /** The content of the post */
  content: string;
  /** The date and time the post was created */
  created_at: string;
  /** The date and time the post was updated */
  updated_at: string;
}

export type PostUserSignupBody = {
  /**
   * The display name of the user
   * @minLength 1
   */
  display_name: string;
};

export type PostUserSignup401AllOfCode =
  (typeof PostUserSignup401AllOfCode)[keyof typeof PostUserSignup401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUserSignup401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostUserSignup401AllOf = {
  code?: PostUserSignup401AllOfCode;
  /** explanation */
  message?: string;
};

export type PostUserSignup401 = ErrorResponse & PostUserSignup401AllOf;

export type PostUserSignup403AllOfCode =
  (typeof PostUserSignup403AllOfCode)[keyof typeof PostUserSignup403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUserSignup403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostUserSignup403AllOf = {
  code?: PostUserSignup403AllOfCode;
  /** explanation */
  message?: string;
};

export type PostUserSignup403 = ErrorResponse & PostUserSignup403AllOf;

export type PostUserSignup404AllOfCode =
  (typeof PostUserSignup404AllOfCode)[keyof typeof PostUserSignup404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUserSignup404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostUserSignup404AllOf = {
  code?: PostUserSignup404AllOfCode;
  /** explanation */
  message?: string;
};

export type PostUserSignup404 = ErrorResponse & PostUserSignup404AllOf;

export type PostUserSignup500AllOfCode =
  (typeof PostUserSignup500AllOfCode)[keyof typeof PostUserSignup500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostUserSignup500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostUserSignup500AllOf = {
  code?: PostUserSignup500AllOfCode;
  /** explanation */
  message?: string;
};

export type PostUserSignup500 = ErrorResponse & PostUserSignup500AllOf;

export type GetUserLogin401AllOfCode =
  (typeof GetUserLogin401AllOfCode)[keyof typeof GetUserLogin401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserLogin401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetUserLogin401AllOf = {
  code?: GetUserLogin401AllOfCode;
  /** explanation */
  message?: string;
};

export type GetUserLogin401 = ErrorResponse & GetUserLogin401AllOf;

export type GetUserLogin403AllOfCode =
  (typeof GetUserLogin403AllOfCode)[keyof typeof GetUserLogin403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserLogin403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetUserLogin403AllOf = {
  code?: GetUserLogin403AllOfCode;
  /** explanation */
  message?: string;
};

export type GetUserLogin403 = ErrorResponse & GetUserLogin403AllOf;

export type GetUserLogin404AllOfCode =
  (typeof GetUserLogin404AllOfCode)[keyof typeof GetUserLogin404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserLogin404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetUserLogin404AllOf = {
  code?: GetUserLogin404AllOfCode;
  /** explanation */
  message?: string;
};

export type GetUserLogin404 = ErrorResponse & GetUserLogin404AllOf;

export type GetUserLogin500AllOfCode =
  (typeof GetUserLogin500AllOfCode)[keyof typeof GetUserLogin500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserLogin500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetUserLogin500AllOf = {
  code?: GetUserLogin500AllOfCode;
  /** explanation */
  message?: string;
};

export type GetUserLogin500 = ErrorResponse & GetUserLogin500AllOf;

export type GetPosts200PostsItemAllOf = {
  user: User;
};

export type GetPosts200PostsItem = Post & GetPosts200PostsItemAllOf;

export type GetPosts200 = {
  posts: GetPosts200PostsItem[];
};

export type GetPosts401AllOfCode =
  (typeof GetPosts401AllOfCode)[keyof typeof GetPosts401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts401AllOf = {
  code?: GetPosts401AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts401 = ErrorResponse & GetPosts401AllOf;

export type GetPosts403AllOfCode =
  (typeof GetPosts403AllOfCode)[keyof typeof GetPosts403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts403AllOf = {
  code?: GetPosts403AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts403 = ErrorResponse & GetPosts403AllOf;

export type GetPosts404AllOfCode =
  (typeof GetPosts404AllOfCode)[keyof typeof GetPosts404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts404AllOf = {
  code?: GetPosts404AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts404 = ErrorResponse & GetPosts404AllOf;

export type GetPosts500AllOfCode =
  (typeof GetPosts500AllOfCode)[keyof typeof GetPosts500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts500AllOf = {
  code?: GetPosts500AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts500 = ErrorResponse & GetPosts500AllOf;

export type PostPostsBody = {
  /**
   * The content of the post
   * @minLength 1
   */
  content: string;
};

export type PostPosts200PostAllOf = {
  user: User;
};

export type PostPosts200Post = Post & PostPosts200PostAllOf;

export type PostPosts200 = {
  post: PostPosts200Post;
};

export type PostPosts401AllOfCode =
  (typeof PostPosts401AllOfCode)[keyof typeof PostPosts401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts401AllOf = {
  code?: PostPosts401AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts401 = ErrorResponse & PostPosts401AllOf;

export type PostPosts403AllOfCode =
  (typeof PostPosts403AllOfCode)[keyof typeof PostPosts403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts403AllOf = {
  code?: PostPosts403AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts403 = ErrorResponse & PostPosts403AllOf;

export type PostPosts404AllOfCode =
  (typeof PostPosts404AllOfCode)[keyof typeof PostPosts404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts404AllOf = {
  code?: PostPosts404AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts404 = ErrorResponse & PostPosts404AllOf;

export type PostPosts500AllOfCode =
  (typeof PostPosts500AllOfCode)[keyof typeof PostPosts500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts500AllOf = {
  code?: PostPosts500AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts500 = ErrorResponse & PostPosts500AllOf;

export type PutPostsPublicIdBody = {
  /**
   * The content of the post
   * @minLength 1
   */
  content?: string;
};

export type PutPostsPublicId200PostAllOf = {
  user: User;
};

export type PutPostsPublicId200Post = Post & PutPostsPublicId200PostAllOf;

export type PutPostsPublicId200 = {
  post: PutPostsPublicId200Post;
};

export type PutPostsPublicId401AllOfCode =
  (typeof PutPostsPublicId401AllOfCode)[keyof typeof PutPostsPublicId401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsPublicId401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsPublicId401AllOf = {
  code?: PutPostsPublicId401AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsPublicId401 = ErrorResponse & PutPostsPublicId401AllOf;

export type PutPostsPublicId403AllOfCode =
  (typeof PutPostsPublicId403AllOfCode)[keyof typeof PutPostsPublicId403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsPublicId403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsPublicId403AllOf = {
  code?: PutPostsPublicId403AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsPublicId403 = ErrorResponse & PutPostsPublicId403AllOf;

export type PutPostsPublicId404AllOfCode =
  (typeof PutPostsPublicId404AllOfCode)[keyof typeof PutPostsPublicId404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsPublicId404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsPublicId404AllOf = {
  code?: PutPostsPublicId404AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsPublicId404 = ErrorResponse & PutPostsPublicId404AllOf;

export type PutPostsPublicId500AllOfCode =
  (typeof PutPostsPublicId500AllOfCode)[keyof typeof PutPostsPublicId500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsPublicId500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsPublicId500AllOf = {
  code?: PutPostsPublicId500AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsPublicId500 = ErrorResponse & PutPostsPublicId500AllOf;

export type DeletePostsPublicId401AllOfCode =
  (typeof DeletePostsPublicId401AllOfCode)[keyof typeof DeletePostsPublicId401AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsPublicId401AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsPublicId401AllOf = {
  code?: DeletePostsPublicId401AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsPublicId401 = ErrorResponse &
  DeletePostsPublicId401AllOf;

export type DeletePostsPublicId403AllOfCode =
  (typeof DeletePostsPublicId403AllOfCode)[keyof typeof DeletePostsPublicId403AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsPublicId403AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsPublicId403AllOf = {
  code?: DeletePostsPublicId403AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsPublicId403 = ErrorResponse &
  DeletePostsPublicId403AllOf;

export type DeletePostsPublicId404AllOfCode =
  (typeof DeletePostsPublicId404AllOfCode)[keyof typeof DeletePostsPublicId404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsPublicId404AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsPublicId404AllOf = {
  code?: DeletePostsPublicId404AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsPublicId404 = ErrorResponse &
  DeletePostsPublicId404AllOf;

export type DeletePostsPublicId500AllOfCode =
  (typeof DeletePostsPublicId500AllOfCode)[keyof typeof DeletePostsPublicId500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsPublicId500AllOfCode = {
  Bad_Request: "Bad Request",
  Unauthorized: "Unauthorized",
  Forbidden: "Forbidden",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsPublicId500AllOf = {
  code?: DeletePostsPublicId500AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsPublicId500 = ErrorResponse &
  DeletePostsPublicId500AllOf;
