/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * backend_app OpenAPI
 * OpenAPI spec version: 1.0.0
 */
export interface Post {
  /**
   * Primary ID
   * @minimum -2147483648
   * @maximum 2147483647
   */
  id: number;
  /** The content of the post */
  content: string;
  /** The date and time the post was created */
  created_at: string;
  /** The date and time the post was updated */
  updated_at: string;
}

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorCode = {
  Bad_Request: "Bad Request",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export interface Error {
  code: ErrorCode;
  /** explanation */
  message: string;
}

export type GetPosts200 = {
  posts: Post[];
};

export type GetPosts404AllOfCode =
  (typeof GetPosts404AllOfCode)[keyof typeof GetPosts404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts404AllOfCode = {
  Bad_Request: "Bad Request",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts404AllOf = {
  code?: GetPosts404AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts404 = Error & GetPosts404AllOf;

export type GetPosts500AllOfCode =
  (typeof GetPosts500AllOfCode)[keyof typeof GetPosts500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPosts500AllOfCode = {
  Bad_Request: "Bad Request",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type GetPosts500AllOf = {
  code?: GetPosts500AllOfCode;
  /** explanation */
  message?: string;
};

export type GetPosts500 = Error & GetPosts500AllOf;

export type PostPostsBody = {
  /**
   * The content of the post
   * @minLength 1
   */
  content: string;
};

export type PostPosts200 = {
  post: Post;
};

export type PostPosts404AllOfCode =
  (typeof PostPosts404AllOfCode)[keyof typeof PostPosts404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts404AllOfCode = {
  Bad_Request: "Bad Request",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts404AllOf = {
  code?: PostPosts404AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts404 = Error & PostPosts404AllOf;

export type PostPosts500AllOfCode =
  (typeof PostPosts500AllOfCode)[keyof typeof PostPosts500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostPosts500AllOfCode = {
  Bad_Request: "Bad Request",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PostPosts500AllOf = {
  code?: PostPosts500AllOfCode;
  /** explanation */
  message?: string;
};

export type PostPosts500 = Error & PostPosts500AllOf;

export type PutPostsIdBody = {
  /**
   * The content of the post
   * @minLength 1
   */
  content?: string;
};

export type PutPostsId200 = {
  post: Post;
};

export type PutPostsId404AllOfCode =
  (typeof PutPostsId404AllOfCode)[keyof typeof PutPostsId404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsId404AllOfCode = {
  Bad_Request: "Bad Request",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsId404AllOf = {
  code?: PutPostsId404AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsId404 = Error & PutPostsId404AllOf;

export type PutPostsId500AllOfCode =
  (typeof PutPostsId500AllOfCode)[keyof typeof PutPostsId500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutPostsId500AllOfCode = {
  Bad_Request: "Bad Request",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type PutPostsId500AllOf = {
  code?: PutPostsId500AllOfCode;
  /** explanation */
  message?: string;
};

export type PutPostsId500 = Error & PutPostsId500AllOf;

export type DeletePostsId404AllOfCode =
  (typeof DeletePostsId404AllOfCode)[keyof typeof DeletePostsId404AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsId404AllOfCode = {
  Bad_Request: "Bad Request",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsId404AllOf = {
  code?: DeletePostsId404AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsId404 = Error & DeletePostsId404AllOf;

export type DeletePostsId500AllOfCode =
  (typeof DeletePostsId500AllOfCode)[keyof typeof DeletePostsId500AllOfCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeletePostsId500AllOfCode = {
  Bad_Request: "Bad Request",
  Not_Found: "Not Found",
  Internal_Server_Error: "Internal Server Error",
} as const;

export type DeletePostsId500AllOf = {
  code?: DeletePostsId500AllOfCode;
  /** explanation */
  message?: string;
};

export type DeletePostsId500 = Error & DeletePostsId500AllOf;
